cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'zsh'
brew 'ack'
brew 'git'
brew 'automake'
brew 'libgpg-error'
brew 'coreutils'
brew 'imagemagick'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'wget'
brew 'libksba'
brew 'libunistring'
brew 'openssh'
brew 'libyaml'
brew 'pkg-config'
brew 'autoconf'
brew 'icu4c'
brew 'libidn2'
brew 'libtool'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'microsoft-edge'
cask 'authy'
cask 'slack'
cask 'spotify'
cask 'iterm2'
cask 'docker'
